### ISSUE TITLE
Doesn't work serverside with nodejs

### ISSUE THREAD

**Issue by abenhamdine** [mohsen1/json-formatter-js#43]
Trying to use in nodejs : 

```
\payroll-app\node_modules\json-formatter-js\dist\json-formatter.js:607
                        return /msie [6-9]\b/.test(window.navigator.userAgent.toLowerCase());
                                                   ^

ReferenceError: window is not defined
    at C:\node-projects\payroll-app\node_modules\json-formatter-js\dist\json-formatter.js:607:31
    at C:\node-projects\payroll-app\node_modules\json-formatter-js\dist\json-formatter.js:602:48
    at module.exports (C:\node-projects\payroll-app\node_modules\json-formatter-js\dist\json-formatter.js:624:69)
    at Object.<anonymous> (C:\node-projects\payroll-app\node_modules\json-formatter-js\dist\json-formatter.js:504:37)
    at __webpack_require__ (C:\node-projects\payroll-app\node_modules\json-formatter-js\dist\json-formatter.js:30:30)
    at Object.<anonymous> (C:\node-projects\payroll-app\node_modules\json-formatter-js\dist\json-formatter.js:65:2)
    at __webpack_require__ (C:\node-projects\payroll-app\node_modules\json-formatter-js\dist\json-formatter.js:30:30)
    at Object.<anonymous> (C:\node-projects\payroll-app\node_modules\json-formatter-js\dist\json-formatter.js:57:19)
    at __webpack_require__ (C:\node-projects\payroll-app\node_modules\json-formatter-js\dist\json-formatter.js:30:30)
    at C:\node-projects\payroll-app\node_modules\json-formatter-js\dist\json-formatter.js:50:18```

**Comment by mohsen1** [comment]
Use jsdom in your server environment. 

Making this to work independently on the server environment would require a lot of work

**Comment by abenhamdine** [comment]
Thx for you response.

> Making this to work independently on the server environment would require a lot of work

Yes, I realised after my first post that the whole code is client-tied.

**Comment by madhur** [comment]
Is there any example of how to make it work with jsdom? I am looking to insert the formatted json inside a html table cell.

**Comment by mohsen1** [comment]
Not the prettiest 
```ts
const { window } = new JSDOM(`...`);

global.window = window

new  JSONFormatter()

```

or 

```ts
with (window) {
  new  JSONFormatter()
}
```

^ this is bad
